spring:
    application:
        name: studify-be

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/studify_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: root
        password: 123456789
        
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true     
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                '[format_sql]': true

server:
    port: 8088


logging:
  level:
    '[org.hibernate.SQL]': debug
    '[org.hibernate.orm.jdbc.bind]': trace

jwt:
  secret: "change-me-please-very-long-secret-key-for-dev"
  access-token-validity: 3600000      # 1h (ms)
  refresh-token-validity: 1209600000  # 14d (ms)


